import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { NextPage } from 'next'
import { getRequestInstance } from "../modules/request"
import useSWR from "swr";
import { features } from 'process'

// const inter = Inter({ subsets: ['latin'] })

// const Page: NextPage = ( {data} ) => {
//   return data.map(
//      (d: any, index:number) => <div>{index}番目のデータ: {d.any_column}</div>
//   )
// }
const Page:NextPage = ({data})=> {
  return <p>{data}</p>
}
Page.getInitialProps = async (ctx: any) => {
 const request = getRequestInstance(Boolean(ctx.req));
 const res = await request.get("data").then(res => res);
 return res.data;
}
export default Page



// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.tsx</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }




	// // モジュールを準備
  // let http = require('http')
  // let {Client} = require('pg');

  // http.createServer(function (req, res) {
  //     // PostgreSQLに接続
  //     let client = new Client({
  //         user: 'postgres',
  //         host: '127.0.0.1',
  //         database: 'db',
  //         password: 'password',
  //         port: 5432
  //     })
  //     client.connect()

  //     // HTTPレスポンスヘッダを出力
  //     res.writeHead(200, {'Content-Type': 'text/html;charset=utf-8'})

  //     // クエリを実行してTABLEタグで出力
  //     let query = client.query(
  //         "select messageId, message, timestamp,userId, withUserId from persons;",
  //          function(err, result) {
  //         res.write('<html><head></head><body><table>');
  //         for(lc = 0; lc < result.rows.length; lc++){
  //             res.write('<tr>');
  //             res.write("<td>"+result.rows[lc].person_id+"</td>" );
  //             res.write("<td>"+result.rows[lc].name+"</td>" );
  //             res.write("<td>"+result.rows[lc].kana+"</td>" );
  //             res.write("<td>"+result.rows[lc].gender+"</td>" );
  //             res.write('</tr>');
  //         }
  //         res.end('</table></body></html>')
  //     });
  // }).listen(8989)

  // export const fetcher = (resource: any, init: any) =>
  // fetch(resource, init).then((res) => res.json());

  // export default function Home() {
  //   const {data, error, isLoading} = useSWR('127.0.0.1:5432/db/postgres', fetcher)
  //   if (error) return <div>failed to load</div>
  // if (isLoading) return <div>loading...</div>

  // return <div>{data.message}</div>
  // }
